services:

  alarms:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alarms:${ALARMS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/newMachine.env
      - ../conf/alarms.env
    networks:
      - mitra
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  alerts:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alerts:${ALERTS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/newMachine.env
      - ../conf/alerts.env
    deploy:
      mode: replicated
      replicas: ${REPLICAS:-1}
    networks:
      - mitra
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

networks:
  mitra:
    external: true
    name: mitra