services:
  mqttin:
    container_name: ${COMPOSE_PROJECT_NAME}-mqttin
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mqtt-inputs:${MQTT_INPUTS_TAG:-latest}
    env_file:
      - ../conf/mqttInputs.env
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  configs:
    container_name: ${COMPOSE_PROJECT_NAME}-configs
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/configs:${CONFIGS_TAG:-latest}
    env_file:
      - ../conf/configs.env
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
     - mitra

networks:
  mitra:
    external: true
    name: mitra