services:
  httpin:
    container_name: ${COMPOSE_PROJECT_NAME}-httpin
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/http-inputs:${HTTP_INPUTS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/httpInputs.env
    deploy:
      mode: replicated
      replicas: 3
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  mqttin:
    container_name: ${COMPOSE_PROJECT_NAME}-mqttin
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mqtt-inputs:${MQTT_INPUTS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/mqttInputs.env
    networks:
      - mitra

  configs:
    container_name: ${COMPOSE_PROJECT_NAME}-configs
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/configs:${CONFIGS_TAG:-latest}
    env_file:
      - ../conf/configs.env
    deploy:
      mode: replicated
      replicas: 3      
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
     - mitra

  events:
    container_name: ${COMPOSE_PROJECT_NAME}-events
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/events:${EVENTS_TAG:-latest}
    env_file:
      - ../conf/common.env
    deploy:
      mode: replicated
      replicas: 3      
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
     - mitra     

networks:
  mitra:
    external: true
    name: mitra