services:
  limits:
    container_name: ${COMPOSE_PROJECT_NAME}-limits
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/limits:${LIMITS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/limits.env
    networks:
     - mitra

  httpin:
    container_name: ${COMPOSE_PROJECT_NAME}-httpin
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/http-inputs:${HTTP_INPUTS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/httpInputs.env
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s      
    networks:
      - mitra

  mqttin:
    container_name: ${COMPOSE_PROJECT_NAME}-mqttin
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mqtt-inputs:${MQTT_INPUTS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/mqttInputs.env
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra