services:
  gateway:
    container_name: ${COMPOSE_PROJECT_NAME}-gateway
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/gateway:${GATEWAY_TAG:-latest}
    env_file:
      - ../conf/license.env
      - ../conf/common.env
    ports:
      - "80:80"
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra