services:
  topics:
    container_name: ${COMPOSE_PROJECT_NAME}-topics
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka-tools:${KAFKA_TOOLS_TAG:-latest}
    env_file:
      - ../conf/topics.env
    networks:
      - mitra

  tables:
    container_name: ${COMPOSE_PROJECT_NAME}-tables
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/tables:${TABLES_TAG:-latest}
    env_file:
      - ../conf/tables.env
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra