services:
  topics:
    container_name: ${COMPOSE_PROJECT_NAME}-topics
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka-tools:${KAFKA_TOOLS_TAG:-latest}
    env_file:
      - ../conf/${CONF_DIR}/topics.env
    networks:
      - mitra

  queries:
    container_name: ${COMPOSE_PROJECT_NAME}-queries
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/queries:${QUERIES_TAG:-latest}
    depends_on:
      topics:
        condition: service_completed_successfully
    env_file:
      - ../conf/${CONF_DIR}/queries.env
    networks:
      - mitra

  tables:
    container_name: ${COMPOSE_PROJECT_NAME}-tables
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/tables:${TABLES_TAG:-latest}
    env_file:
      - ../conf/${CONF_DIR}/tables.env
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra