services:
  topics:
    container_name: ${COMPOSE_PROJECT_NAME}-topics
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka-tools:${KAFKA_TOOLS_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/topics.env
    networks:
      - mitra

  queris:
    container_name: ${COMPOSE_PROJECT_NAME}-queris
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/queries:${QUERIES_TAG:-latest}
    depends_on:
      topics:
        condition: service_completed_successfully
    env_file:
      - ../conf/common.env
      - ../conf/queries.env
    networks:
      - mitra

  tables:
    container_name: ${COMPOSE_PROJECT_NAME}-tables
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/tables:${TABLES_TAG:-latest}
    env_file:
      - ../conf/common.env
      - ../conf/tables.env
    networks:
      - mitra

networks:
  mitra:
    external: true
    name: mitra