services:

  alerts:
    container_name: ${COMPOSE_PROJECT_NAME}-alerts
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alerts:${ALERTS_TAG:-latest}
    env_file:
      - ./conf/common.env
      - ./conf/alerts.env
    networks:
      - mitra
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  alarms:
    container_name: ${COMPOSE_PROJECT_NAME}-alarms
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alarms:${ALARMS_TAG:-latest}
    env_file:
      - ./conf/common.env
      - ./conf/alarms.env
    networks:
      - mitra
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  events:
    container_name: ${COMPOSE_PROJECT_NAME}-events
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/streamer:${STREAMER_TAG:-latest}
    depends_on:
      alarms:
        condition: service_healthy
      alerts:
        condition: service_healthy
    env_file:
      - ./conf/common.env
      - ./conf/events.env
    networks:
      - mitra
    healthcheck:
      test: /work/health
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  persistd:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/persist:${PERSIST_TAG:-latest}
    depends_on:
      alarms:
        condition: service_healthy
      alerts:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./conf/common.env
      - ./conf/persistData.env
    networks:
      - mitra
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "/health/index.js"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  persistr:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/persist:${PERSIST_TAG:-latest}
    depends_on:
      alarms:
        condition: service_healthy
      alerts:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./conf/common.env
      - ./conf/persistAlerts.env
    networks:
      - mitra
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "/health/index.js"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

  persistm:
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/persist:${PERSIST_TAG:-latest}
    depends_on:
      alarms:
        condition: service_healthy
      alerts:
        condition: service_healthy
    deploy:
      mode: replicated
      replicas: 1
    env_file:
      - ./conf/common.env
      - ./conf/persistAlarms.env
    networks:
      - mitra
    healthcheck:
      test: ["CMD", "/nodejs/bin/node", "/health/index.js"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s

networks:
  mitra:
    external: true
    name: mitra