version: '3.5'

services:
  zookeeper:
    container_name: ${COMPOSE_PROJECT_NAME}-zookeeper
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/zookeeper:${ZOOKEEPER_TAG:-latest}
    env_file:
      - ./conf/zk.env
    restart: always

  broker:
    container_name: ${COMPOSE_PROJECT_NAME}-broker
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka:${KAFKA_TAG:-latest}
    depends_on:
      - zookeeper
    env_file:
      - ./conf/kafka.env
    restart: always

  pause:
    container_name: ${COMPOSE_PROJECT_NAME}-pause
    image: busybox
    depends_on:
      - broker
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      " sleep 30 "

  init:
    container_name: ${COMPOSE_PROJECT_NAME}-init-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka:${KAFKA_TAG:-latest}
    depends_on:
      - pause
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      /etc/scripts/init.sh
      "
    env_file:
      - ./conf/init.env
    volumes:
      - ./scripts:/etc/scripts

  payload:
    container_name: ${COMPOSE_PROJECT_NAME}-payload-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/payload:${PAYLOAD_TAG:-latest}
    depends_on:
      - init
    env_file:
      - ./conf/common.env
      - ./conf/payload.env
      - ./conf/sasl-auth.env
      - ./conf/license.env
    ports:
      - ${HOST_PAYLOAD_PORT}:${CONT_PAYLOAD_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  limits:
    container_name: ${COMPOSE_PROJECT_NAME}-limits-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/limits:${LIMITS_TAG:-latest}
    depends_on:
      - init
    env_file:
      - ./conf/common.env
      - ./conf/limits.env
      - ./conf/sasl-auth.env
    ports:
      - ${HOST_LIMITS_PORT}:${CONT_LIMITS_PORT}
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:9090/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  alarms:
    container_name: ${COMPOSE_PROJECT_NAME}-alarms-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alarms:${ALARMS_TAG:-latest}
    depends_on:
      - payload
    env_file:
      - ./conf/common.env
      - ./conf/alarms.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/q/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  alerts:
    container_name: ${COMPOSE_PROJECT_NAME}-alerts-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/alerts:${ALERTS_TAG:-latest}
    depends_on:
      - payload
    env_file:
      - ./conf/common.env
      - ./conf/alerts.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/q/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  merger:
    container_name: ${COMPOSE_PROJECT_NAME}-merger-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/merger:${MERGER_TAG:-latest}
    depends_on:
      - alarms
      - alerts
    env_file:
      - ./conf/common.env
      - ./conf/merger.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/q/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  streamer:
    container_name: ${COMPOSE_PROJECT_NAME}-streamer-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/streamer:${STREAMER_TAG:-latest}
    depends_on:
      - merger
    env_file:
      - ./conf/common.env
      - ./conf/streamer.env
    healthcheck:
      test: wget --no-verbose --tries=1 http://localhost:8080/q/health || exit 1
      interval: 2s
      timeout: 1s
      retries: 3
      start_period: 10s

  dashboard:
    container_name: ${COMPOSE_PROJECT_NAME}-dashboard-${MACHINE_ID:-M001}
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/dashboard:${DASHBOARD_TAG:-latest}
    depends_on:
      - streamer
    env_file:
      - ./conf/common.env
      - ./conf/dashboard.env
    ports:
      - ${HOST_UI_PORT}:${CONT_UI_PORT}
