services:
  init:
    container_name: ${COMPOSE_PROJECT_NAME}-init
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/kafka-tools:${KAFKA_TOOLS_TAG:-latest}
    env_file:
      - ./conf/common.env
      - ./conf/init.env
    networks:
      - broker

networks:
  broker:
    external: true
    name: broker