services:
  broker:
    container_name: ${COMPOSE_PROJECT_NAME}-broker
    image: confluentinc/cp-kafka:${KAFKA_TAG:-latest}
    env_file:
      - ./conf/common.env
      - ./conf/broker.env
    healthcheck:
      test: ["CMD", "kafka-topics", "--list", "--bootstrap-server", "localhost:9092"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra

  ksqldb:
    container_name: ${COMPOSE_PROJECT_NAME}-ksqldb
    image: confluentinc/ksqldb-server:${KAFKA_SQLDB_TAG:-latest}
    depends_on:
      broker:
        condition: service_healthy
    env_file:
      - ./conf/common.env
      - ./conf/ksql.env
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088"]
      interval: 2s
      timeout: 30s
      retries: 3
      start_period: 10s
    networks:
      - mitra
  
  mqtt:
    container_name: ${COMPOSE_PROJECT_NAME}-mqtt
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mosquitto:${MQTT_PAYLOAD_TAG:-latest}
    networks:
      - mitra

  mysql:
    container_name: ${COMPOSE_PROJECT_NAME}-mysql
    image: ${CONTAINER_REGISTRY}/${CONTAINER_REPOSITORY}/mysql:${MYSQL_PAYLOAD_TAG:-latest}
    environment:
      - ./conf/common.env
    networks:
      - mitra

networks:
  mitra:
    name: mitra